# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-29 10:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbrake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jserror',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 12, 29, 10, 51, 46, 346085)),
            preserve_default=False,
        ),
    ]
