# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-29 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbrake', '0002_jserror_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='jserror',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jserror',
            name='status',
            field=models.CharField(choices=[(b'new', b''), (b'resolved', b''), (b'watching', b'')], default=b'new', max_length=16),
        ),
    ]
