# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-29 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbrake', '0003_auto_20161229_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jserror',
            name='status',
            field=models.CharField(choices=[(b'new', b'new'), (b'resolved', b'resolved'), (b'watching', b'watching')], default=b'new', max_length=16),
        ),
    ]
